#!/usr/bin/env bun

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

/**
 * Sync API documentation to Kiro steering for AI context
 * 
 * This script automatically copies the generated API.md to .kiro/steering
 * so that AI assistants can understand the API without needing to ask.
 */
async function syncAPIDocsToSteering() {
  console.log('📋 Syncing API Documentation to Kiro Steering...\n');

  try {
    // Paths
    const apiDocsPath = join(process.cwd(), 'docs', 'API.md');
    const steeringDir = join(process.cwd(), '..', '.kiro', 'steering');
    const steeringFilePath = join(steeringDir, 'API_REFERENCE.md');

    // Read API docs
    console.log('📖 Reading API documentation...');
    const apiDocs = readFileSync(apiDocsPath, 'utf-8');

    // Create steering directory if not exists
    mkdirSync(steeringDir, { recursive: true });

    // Create steering file with front-matter
    console.log('✍️  Creating steering file...');
    const steeringContent = `---
inclusion: auto
description: Complete API reference for LinVNix backend - automatically synced from generated docs
keywords: api, endpoints, rest, http, backend, swagger
---

# LinVNix API Reference (Auto-Generated)

> **Note:** This file is automatically generated and synced from \`backend/docs/API.md\`.
> Do not edit manually. Run \`npm run docs:sync\` to update.

${apiDocs}
`;

    // Write to steering
    writeFileSync(steeringFilePath, steeringContent);

    console.log('✅ API Documentation synced to Kiro steering!\n');
    console.log(`📄 File: ${steeringFilePath}\n`);
    console.log('🤖 AI assistants can now access API docs automatically via steering context.\n');
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

// Run
syncAPIDocsToSteering();
